from PegSolitaire.Agent.FunctionApproximator import FunctionApproximator
from PegSolitaire.Agent.EligibilityTable import EligibilityTable
from PegSolitaire.Agent.TableFunctionApproximator import TableFunctionApproximator
from PegSolitaire.Agent.SplitGD import SplitGD
from PegSolitaire.Agent.NNFunctionApproximator import NNFunctionApproximator
from PegSolitaire.Agent.Actor import Actor
from PegSolitaire.Agent.Critic import Critic
from PegSolitaire.Agent.ACMAgent import ACMAgent
